# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: asterank-ruby 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "asterank-ruby"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Jose Irizarry"]
  s.date = "2014-03-23"
  s.description = "Ruby Client to connect to Asterank APIs"
  s.email = "jose@spaceappspr.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "asterank-ruby.gemspec",
    "lib/asterank-ruby.rb",
    "lib/asterank-ruby/api/asterank.rb",
    "lib/asterank-ruby/api/kepler.rb",
    "lib/asterank-ruby/api/mpc.rb",
    "lib/asterank-ruby/api/skymorph.rb",
    "lib/asterank-ruby/client.rb",
    "lib/asterank-ruby/mongo_party.rb",
    "lib/asterank-ruby/version.rb",
    "test/helper.rb",
    "test/test_asterank.rb"
  ]
  s.homepage = "http://github.com/crm114/asterank-ruby-client"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.0"
  s.summary = "Asterank Ruby Client"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, ["~> 0.13.0"])
      s.add_runtime_dependency(%q<origin>, ["~> 2.1.0"])
      s.add_runtime_dependency(%q<activesupport>, ["~> 4.0.4"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<httparty>, ["~> 0.13.0"])
      s.add_dependency(%q<origin>, ["~> 2.1.0"])
      s.add_dependency(%q<activesupport>, ["~> 4.0.4"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<httparty>, ["~> 0.13.0"])
    s.add_dependency(%q<origin>, ["~> 2.1.0"])
    s.add_dependency(%q<activesupport>, ["~> 4.0.4"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

